### ISSUE TITLE
Error: Unknown filetype descriptor: public.tiff

### ISSUE THREAD

**Issue by MartyPortatoes** [steilerDev/icloud-photos-sync#132]
Absolutely love what you're doing here! When deploying the container I'm able to auth w/ iCloud however the the container exits with the attached error. Presumably it seems to not care of the .TIFF extension. Thanks!

[_photo-sync_logs-2.txt](https://github.com/steilerDev/icloud-photos-sync/files/10325549/_photo-sync_logs-2.txt)

**Comment by steilerDev** [comment]
Yeah - Apple does not have a list of all potential extensions, so I hardcoded an error there. 

I'm currently working on my v1 release and will include it.

**Comment by steilerDev** [comment]
For a temporary fix go to `app/bin/lib/photos-library/model/file-type.js` and add the file descriptor and the correct file extension into the `EXT` object - this should allow you to sync your files for now :)

**Comment by MartyPortatoes** [comment]
Awesome, thanks! I'll try that now! Im not much help on the dev side of things (work in ops) but will help out however I can.

**Comment by steilerDev** [comment]
Have a look at https://github.com/steilerDev/icloud-photos-sync/pull/125 - this one adds support for `gif`

This list of file extensions is one examples of help I need from other people - simply understanding whats out there :) 

Always looking for feedback on docs and UX - also: the `dev` branch is where I am significantly ahead of compared to the main one

**Comment by steilerDev** [comment]
Fixed by [ab58e96](https://github.com/steilerDev/icloud-photos-sync/commit/ab58e96a8a4e62936bfa045548e0199d197f5397)
