### ISSUE TITLE
error: Unknown filetype descriptor: com.adobe.raw-image

### ISSUE THREAD

**Issue by MartyPortatoes** [steilerDev/icloud-photos-sync#133]
This one looks like its for the .DNG extension 
[_photo-sync_logs-3.txt](https://github.com/steilerDev/icloud-photos-sync/files/10326092/_photo-sync_logs-3.txt)

**Comment by steilerDev** [comment]
Fixed by [ab58e96](https://github.com/steilerDev/icloud-photos-sync/commit/ab58e96a8a4e62936bfa045548e0199d197f5397)
