### ISSUE TITLE
Unknown filetype descriptor: com.apple.m4v-video

### ISSUE THREAD

**Issue by MartyPortatoes** [steilerDev/icloud-photos-sync#140]
Been out of town most of the weekend and didn't get a chance to test all the formats before you posted the changes but on the video side: .M4V .MP4 .3GP .AVI and .MOV are supported in the Photos app.

For Photos, I think this should be a fairly comprehensive list but ill have to test each one to say for sure

JPG (.jpg, .jpeg, .jpe .jif, .jfif, .jfi)
JPEG 2000 (.jp2, .j2k, .jpf, .jpx, .jpm, .mj2)
PNG (.png)
GIF (.gif)
WEBP (.webp)
TIFF (.tiff, .tif)
PSD (.psd)
RAW (.raw, .arw, .cr2, .nrw, .k25. .dng)
BMP (.bmp, .dib)
HEIF (.heif, .heic)
SVG (.svg, .svgz)

[_photo-sync_logs-4.txt](https://github.com/steilerDev/icloud-photos-sync/files/10333866/_photo-sync_logs-4.txt)

**Comment by steilerDev** [comment]
The problem is, that I could not find a list of Filetype descriptors to Filetypes (what `com.apple.m4v-video` is for `.m4v`) - if we could get this list, the app could be more comprehensive
