### ISSUE TITLE
Docker Compose Pull unset variable

### ISSUE THREAD

**Issue by berlingoff** [steilerDev/icloud-photos-sync#186]
When issuing ‘docker compose pull’ I get a message that says “ WARN[0000] The "tvl" variable is not set. Defaulting to a blank string.”

My AppleID password has a ‘$’ before ‘tvl’ which are the last characters.

**Comment by steilerDev** [comment]
In your `docker-compose.yml` it seems that '$' signs will be interpreted as variables if not either escaped or in single quotes. See [this SO](https://stackoverflow.com/a/22235064/3763870) for context.

So given your string of:
```
[...]
    environment:
      APPLE_ID_PWD: "asdf$tvl"
[...]
```
you should either use
```
[...]
    environment:
      APPLE_ID_PWD: 'asdf$tvl'
[...]
```
or
```
[...]
    environment:
      APPLE_ID_PWD: "asdf\$tvl"
[...]
```

**Comment by berlingoff** [comment]
[...]
    environment:
      APPLE_ID_PWD: 'asdf$tvl'
[...]
Results in WARN[0000] The "tvl" variable is not set. Defaulting to a blank string.

[...]
    environment:
      APPLE_ID_PWD: "asdf\$tvl"
[...]
Results in yaml: line 9: found unknown escape character

**Comment by steilerDev** [comment]
It seems `docker-compose` does not follow the yaml standard, can you [try with double $ signs](https://stackoverflow.com/a/40621373/3763870):
```
[...]
environment:
    APPLE_ID_PWD: "asdf$$tvl"
[...]
