### ISSUE TITLE
Entrypoint does not allow overwrite

### ISSUE THREAD

**Issue by maxsz** [steilerDev/icloud-photos-sync#197]
https://github.com/steilerDev/icloud-photos-sync/blob/99f694c3540839903bac97fddfcb386caa499c54/docker/Dockerfile#L21

This will now always run in daemon mode. I am trying to run it on synology and there is only a way to specify the command, which is now impossible.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/540025/219854749-75839db9-ecb9-48c0-8d05-2c0d2c63cf7f.png">

**Comment by steilerDev** [comment]
This is the same behaviour as previously? What do you try to achieve, which is no longer possible.

I'm not too familiar with Synology's Docker implementation, however it is possible to overwrite the entrypoint of a docker container.

**Comment by maxsz** [comment]
Previously the ENTRYPOINT did not contain any commands: https://github.com/steilerDev/icloud-photos-sync/blob/80c06207e02990fd19a808770b71a9b519b5a53f/docker/Dockerfile#L21

Best practice is to separate the command from the entry point, like so: 
ENTRYPOINT ["icloud-photos-sync"]
CMD ["daemon"]

The command can then be easily overwritten from the CLI (or in my case Synology). Where as now it will only ever run in daemon mode.

Thanks for considering!

**Comment by steilerDev** [comment]
That makes sense! I completely forgot about `CMD` - fixed in 444fa332f285af3aa80a5fec77d02325c18fc289

Thank you!
