### ISSUE TITLE
Security Key MFA Support

### ISSUE THREAD

**Issue by steilerDev** [steilerDev/icloud-photos-sync#207]
I'm in a similar position with advanced data protection and a yubikey on my Apple ID. With this combination of security settings, the sign in prompts I receive on other devices don't have MFA codes, but rather just "ok" or "that wasn't me". 

_Originally posted by @krubenok in https://github.com/steilerDev/icloud-photos-sync/issues/202#issuecomment-1456795183_

**Comment by steilerDev** [comment]
I currently don't have an account setup using YubiKey (neither do I plan to do so). 

In order to investigate this use case, I need support from someone with this setup.

I need an [HAR file](https://support.zendesk.com/hc/en-us/articles/4408828867098-Generating-a-HAR-file-for-troubleshooting) filtered to `Fetch/XHR` from the authentication against the iCloud WebUI - based on that I might be able to understand what needs to change in order to support this (Full disclosure: Keep in mind that this HAR file might contain sensitive data - unless you know how to purge it, you need to trust me that I won't abuse this - Please note: since the MFA trust token is location/IP specific I probably won't be able to use the data from those requests anyway)

**Comment by krubenok** [comment]
I'll take a more careful look at the contents of a HAR file this weekend and determine if I'm ok sending that over. I have a few other ideas if that turns out to be a no.

**Comment by steilerDev** [comment]
Could you maybe check if there is some sort of pulling happening while the WebUI waits for you to confirm the request?

**Comment by steilerDev** [comment]
Side note: [I documented the sign in flow and all the important data](https://steilerdev.github.io/icloud-photos-sync/dev/api/)

So that's probably the data you want to purge - most important your password and the `X-Apple-TwoSV-TrustToken` header. This is the token that allows bypassing 2FA.

**Comment by steilerDev** [comment]
Closing due unclear path of feasibility (e.g. how to read security key from the cli tool that most likely will run on a separated machine)

Please re-open in case there are no insights available.

**Comment by dvtkrlbs** [comment]
I plan to try to reverse engineer the process the Windows App uses for authentication (they probably use the same flow that is used by apple devices) If I find any info on that will share cuz that flow would allow signon even on security keys or with advanced data protection (afaik you don't need to enable web access with the windows app)
