### ISSUE TITLE
iCloud China Support

### ISSUE THREAD

**Issue by Sowevo** [steilerDev/icloud-photos-sync#286]
**Checklist before opening an issue**
- [x] Tried the sync a couple of times and the issue is persisting
- [x] Checked out [known issues](https://github.com/steilerDev/icloud-photos-sync/labels/known%20issue)
- [x] Enabled [crash and error reporting](https://steilerdev.github.io/icloud-photos-sync/user-guides/error-reporting/)

**Describe the bug**

hello, I'm from China,
Using iCloud in China will have another domain name https://www.icloud.com.cn
If you use https://www.icloud.com directly, a 302 error will occur

I try to directly modify the domain name in the source code `constants.ts`, it can work normally after modification

https://github.com/steilerDev/icloud-photos-sync/blob/f895d9aaa51f2646c8aade0d43175b89e43e2c48/app/src/lib/icloud/constants.ts#L46-L51

**Error code**

Share the Error Code generated upon the crash

```
Experienced fatal error at 2023/7/8 04:15:47: APP_SYNC (FATAL): Sync failed caused by AUTH_FAILED (FATAL): iCloud Authentication failed caused by AUTH_ACCOUNT_SETUP (FATAL): Unable to setup iCloud Account caused by Request failed with status code 302 (Error Code: 9d68a789-8bfb-40cf-982a-5032f67b4a9c) 
```

**Logs**

Please paste the log file (preferably with `LOG_LEVEL=debug`), located in `.icloud-photos-sync.log`, stored in the `DATA_DIR`.

```

```

**Operating environment**
 - OS: [e.g. Debian 10]
 - Version: [e.g. 1.0.0]
 - Execution environment: [e.g. docker]

**Comment by Sowevo** [comment]
Maybe add an option to modify this parameter

**Comment by steilerDev** [comment]
As I don't have access to a Chinese iCloud account, I would need someone from China implementing this feature - no way for me to test or validate.

Happy to point in the right directions, but this would be a feature that needs to be supplied by the community with access to this.

**Comment by steilerDev** [comment]
@Sowevo since I don't have an iCloud China account - could you please try and confirm by setting `--region china` / `REGION="china"`?

**Comment by Sowevo** [comment]
> @Sowevo since I don't have an iCloud China account - could you please try and confirm by setting `--region china` / `REGION="china"`?

After my try, this option works fine, thank you very much

**Comment by steilerDev** [comment]
Awesome, thanks for confirming - closing this issue.
