### ISSUE TITLE
Feature Request: Consistency check

### ISSUE THREAD

**Issue by lonevvolf** [steilerDev/icloud-photos-sync#291]
**Describe the feature**

I have a large library with other 300k photos.  During syncing, I occasionally got breaks in the process which resulted in having to force unlock.  I have a concern that maybe some larger videos, etc. may not be transferred completely.  It would be interesting to run a consistency check on all files to ensure they match the server versions.  Is this done automatically in some way?  Since I imagine this can take a long time with so many files, maybe it needs a dedicated command?

**Comment by steilerDev** [comment]
When syncing the library I am loading all local assets, by reading the files. This is done by [looking at the creation time and size (not the content)](https://github.com/steilerDev/icloud-photos-sync/blob/f895d9aaa51f2646c8aade0d43175b89e43e2c48/app/src/lib/photos-library/model/asset.ts#L227).

Apple provides 'checksum' field within the API, but I have yet to [figure out how to calculate this checksum](https://github.com/steilerDev/icloud-photos-sync/blob/f895d9aaa51f2646c8aade0d43175b89e43e2c48/app/src/lib/photos-library/model/asset.ts#L270] - this would provide a really reliable consistency check, unfortunately I'm out of ideas.

On the library lock errors: This is a very simple locking logic, that was implemented to make sure that two instances of the sync engine are not accessing the file system at the same time - if you are sure no other instance runs, it's safe to remove the lock manually.

**Comment by steilerDev** [comment]
I've created a separate issue (https://github.com/steilerDev/icloud-photos-sync/issues/354) to explain my proposal for a new library version that should resolve this issue. Would therefore love to get your feedback on there and going to close this issue for now. Please re-open if you don't think it is covered by this initiative.
