### ISSUE TITLE
Your Apple ID was used to sign in to iCloud via a web browser.

### ISSUE THREAD

**Issue by lonevvolf** [steilerDev/icloud-photos-sync#292]
**Checklist before opening an issue**
- [X] Tried the sync a couple of times and the issue is persisting
- [X] Checked out [known issues](https://github.com/steilerDev/icloud-photos-sync/labels/known%20issue)
- [X] Enabled [crash and error reporting](https://steilerdev.github.io/icloud-photos-sync/user-guides/error-reporting/)

**Describe the bug**

Every time the sync runs, I get an email from Apple saying:
"Your Apple ID was used to sign in to iCloud via a web browser."

I checked the docs, but didn't see any way to indicate to Apple that the "browser" should be trusted.

**Error code**

NA

**Logs**

NA

**Operating environment**
 - OS: Synology
 - Version: 1.1.1-beta3
 - Execution environment: docker

**Comment by steilerDev** [comment]
See PR #240. 

As a workaround, you can configure server side rules in your email provider to move them out of the way (this is how I'm currently handling thise)

**Comment by steilerDev** [comment]
`HeaderJar` and global `NetworkManager` are now persisting cookies between scheduled sync executions. It seems the `aasp` cookie in connection with the `sessionToken` are suppressing this email. This was added with [`1.2.0-nightly.6`](https://github.com/steilerDev/icloud-photos-sync/releases/tag/v1.2.0-nightly.6).

Currently those cookies are not persisted between process restarts (not sure if it should) - please check it out and provide feedback.

**Comment by steilerDev** [comment]
[v1.2.0](https://github.com/steilerDev/icloud-photos-sync/releases/tag/v1.2.0) only sends this notification after a restart and/or after the session expires (after what appears to be thirty days) - closing this

**Comment by lonevvolf** [comment]
I am still getting this when running a manual sync command on an already running container in v.1.2.0.  Is this expected behavior?

**Comment by steilerDev** [comment]
Yes, session info is held in memory - so not shared between processes.

Only daemon mode shares between sync executions

**Comment by undaunt** [comment]
@steilerDev Is it possible to persist this to disk similar to the implementation by i[cloud-photos-downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader)? In the event I need to reboot the host or similar keeping it in memory will cause it to re-trigger prior to 30 days.

**Comment by steilerDev** [comment]
It's technically possible, but I think I don't want to circumvent this security feature. If someone would be able to access your resource file, they could login and authenticate unnoticed - by keeping this information only in memory you would get notified in case someone logs in using your trust token.

**Comment by undaunt** [comment]
That is a fair point. I was mostly considering wife factor if I’m running
watchtower on my containers, rebooting for random reasons, etc. Could you
consider this as an option that would need to manually be specified via a
flag, and by default remains in memory only?

Adam M. Flagg
