### ISSUE TITLE
Limit of 198 albums

### ISSUE THREAD

**Issue by lonevvolf** [steilerDev/icloud-photos-sync#294]
**Checklist before opening an issue**
- [X] Tried the sync a couple of times and the issue is persisting
- [X] Checked out [known issues](https://github.com/steilerDev/icloud-photos-sync/labels/known%20issue)
- [X] Enabled [crash and error reporting](https://steilerdev.github.io/icloud-photos-sync/user-guides/error-reporting/)

**Describe the bug**

No matter what, the sync only creates 198 albums in the file structure.  If I remove two albums from my library on the server, for instance, the next two will be created on the next sync (and 2 removed from local filesystem).

**Error code**

`DEBUG Sync-Engine: Adding 0 remote entities, removing 0 local entities, keeping 198 local entities`

**Logs**

`DEBUG Sync-Engine: Adding 0 remote entities, removing 0 local entities, keeping 198 local entities`

**Operating environment**
 - OS: Synology DSM
 - Version: 1.1.1-beta.3
 - Execution environment: docker

**Comment by ryan-adler** [comment]
Just checking the docs, I see the note:
> In order to test the split of queries, we need at least 200 pictures in our test environment.

Also the code line:
`export const MAX_RECORDS_LIMIT = 198;`

I assume this has something to do with the albums issue.  Perhaps creating 200 albums in the test environment would be useful to test this limit as well.

**Comment by lonevvolf** [comment]
Just checking the docs, I see the note:

> In order to test the split of queries, we need at least 200 pictures in our test environment.

Also the code line:
`export const MAX_RECORDS_LIMIT = 198;`

I assume this has something to do with the albums issue. Perhaps creating 200 albums in the test environment would be useful to test this limit as well.

Note: sorry, had to report with correct account  :)

**Comment by steilerDev** [comment]
I will probably address this deficiency with #354 - don't want to touch that part of the code given that I most likely will rework the whole logic very soon.

**Comment by steilerDev** [comment]
Closing this in favour of #364
