### ISSUE TITLE
LIBRARY_ASSET_MODIFICATION_TIME: File's modification time does not match iCloud record

### ISSUE THREAD

**Issue by lonevvolf** [steilerDev/icloud-photos-sync#342]
### Describe the issue

For 5 files in my library, I am getting this error.  I tried deleting one and letting it redownload, but got the same result.  For reference, the exact times are:
modification time 1695057324592.1387, iCloud 1668422553947
modification time 1695057328166.1726, iCloud 1668422553951
modification time 1695057328247.1733, iCloud 1668422553951
modification time 1695057330647.1963, iCloud 1668422553953
modification time 1695057331974.209, iCloud 1668422553954

### How to reproduce the behavior?

Unclear - not sure why it's only on certain files.

### Error Code

LIBRARY_ASSET_MODIFICATION_TIME

### Relevant log output

```shell-script
[2023-09-18T17:15:22.602Z] WARN RuntimeWarning: Error while verifying asset AerVe2Qx/XXXXXXXX: LIBRARY_ASSET_SIZE: File's size does not match iCloud record (/opt/icloud-photos-library/_Shared-Photos/AerVe2Qx_XXXXXXXX.jpeg size 225280, iCloud 4066359)

(I've redacted the asset name)
```

### Operating system

Synology

### Execution environment

docker

### icloud-photos-sync version

1.2.0

### Checklist

- [X] This is an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/beta/CONTRIBUTING.md#-found-a-bug) and not [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question) or [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature)
- [X] The sync was performed a couple of times and the issue is persisting and consistent
- [X] Checked out [open and known issues](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28bug%29%2Cclass%28improvement%29%2C%22class%28known+issue%29%22)
- [X] Enabled [crash and error reporting](https://steilerdev.github.io/icloud-photos-sync/user-guides/error-reporting/)

**Comment by steilerDev** [comment]
Hmm - why would 5 files not get their date updated?

Anything those files have in common? Weird characters in the name maybe?

**Comment by steilerDev** [comment]
Probably, yes - let's put this on hold 👍

**Comment by steilerDev** [comment]
I've created a separate issue (https://github.com/steilerDev/icloud-photos-sync/issues/354) to explain my proposal for a new library version that should resolve this issue. Looking forward to your feedback there and will close this issue for now - feel free to re-open in case you feel like the bug described here is no properly addressed.
