### ISSUE TITLE
exec format error(aarch64) rassberry pi 5

### ISSUE THREAD

**Issue by 1Jo1** [steilerDev/icloud-photos-sync#456]
### Describe the issue

When I run docker on my arm64 I'm getting exec executable error: 
```exec /usr/local/bin/icloud-photos-sync: exec format error```

### How to reproduce the behavior?

just run docker the image on arm64
```docker run -it steilerdev/icloud-photos-sync ```

### Error Code

exec error

### Relevant log output

```shell-script
/usr/local/bin/icloud-photos-sync: exec format error
```

### Operating system

ubuntu 23 arm64

### Execution environment

docker

### icloud-photos-sync version

v1.3.0

### Checklist

- [X] This is an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/beta/CONTRIBUTING.md#-found-a-bug) and not [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question) or [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature)
- [X] The sync was performed a couple of times and the issue is persisting and consistent
- [X] Checked out [open and known issues](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28bug%29%2Cclass%28improvement%29%2C%22class%28known+issue%29%22)
- [X] Enabled [crash and error reporting](https://icps.steiler.dev/user-guides/cli/#enable-crash-reporting)

**Comment by 1Jo1** [comment]
I think there is no arm64 support for docker, however there is arm64 release package
when I run ```docker manifest inspect steilerdev/icloud-photos-sync``` 
```
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 7628,
		"digest": "sha256:acc52dbf561212ce791e6e654a6af05e843736641311bc2103319b492101f4c2"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 3401967,
			"digest": "sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 47879767,
			"digest": "sha256:940e130f7dfab921c014dde20cc226266f7b12ca39c90eee5f20b8b95886e04d"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 2342573,
			"digest": "sha256:ec4aadec66232e35f8f751349cb85e4268dea8246ad5fe64b4846d3c1a3f5918"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 451,
			"digest": "sha256:8e83dfb4a0ff093c1c2f41356192c06571d592b123c45f375e8cbcfe51bc5ff5"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 3147079,
			"digest": "sha256:f529790b1f48ac87624dc0e3578376641729c86222e5441bbb4658ab7a77280b"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 128365,
			"digest": "sha256:4d7cf78267c1235b8d570d2ed040fb74f621110a710d47d6d181623960adadff"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 204,
			"digest": "sha256:20b1ff34c274ee0664c0ce1bc5d3e9bd42283d8db7f1cd8246bec2d3317abac7"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 9609843,
			"digest": "sha256:97016a7a65d1d74b82f46283a457c098c54db350ea4978567579873495a41806"
		}
	]
}
```
it seems this docker image doesn't support multi architecture

**Comment by steilerDev** [comment]
Hey @1Jo1 ,

indeed, I'm also building for the arm64 platform, however [publishing this version is not possible through the current CI setup](https://github.com/docker/buildx/issues/1152). The tar archive of the arm64 build of this image is available from the [Github releases](https://github.com/steilerDev/icloud-photos-sync/releases) and can be loaded using `docker load --input <fileName>`.
