### ISSUE TITLE
Can't find album on archive

### ISSUE THREAD

**Issue by tomwilde** [steilerDev/icloud-photos-sync#560]
### Describe the issue

Having successfully synced I attempted to archive and ran into problems.

### How to reproduce the behavior?

I invoked the command:

```
docker exec -t photos-sync icloud-photos-sync archive --remote-delete --enable-crash-reporting --log-level debug /opt/icloud-photos-library/_All-Photos
```

With the docker image containing the following volume mapped files:
```
1736e3892b59:/opt/icloud-photos-library$ ls -la
total 768
drwxr-xr-x    7 node     node          4096 Aug  2 08:11 .
drwxr-xr-x    1 1001     127           4096 Aug  1 19:28 ..
drwxr-xr-x    2 node     node          4096 Aug  1 20:19 .5AB5F901-60E3-4819-ACFB-5FEE639E1453
drwxr-xr-x    2 node     node          4096 Aug  1 20:19 .CE86F307-A7A1-4C72-99AE-0BC6AC2E420B
-rw-r--r--    1 node     node           293 Aug  2 08:11 .icloud-photos-sync
-rw-r--r--    1 node     node         14021 Aug  1 15:37 .icloud-photos-sync.har
-rw-r--r--    1 node     node        557818 Aug  2 08:11 .icloud-photos-sync.log
lrwxrwxrwx    1 node     node            37 Aug  1 20:19 Family -> .CE86F307-A7A1-4C72-99AE-0BC6AC2E420B
lrwxrwxrwx    1 node     node            37 Aug  1 20:19 WhatsApp -> .5AB5F901-60E3-4819-ACFB-5FEE639E1453
drwxr-xr-x    2 node     node        176128 Aug  2 01:00 _All-Photos
drwxr-xr-x    3 node     node          4096 Aug  1 19:29 _Archive
drwxr-xr-x    2 node     node          4096 Aug  1 19:29 _Shared-Photos
```

Which came back with an error:
```
Archiving local path /opt/icloud-photos-library/_All-Photos
Error: APP_ARCHIVE: Archive failed caused by EINVAL: invalid argument, readlink '/opt/icloud-photos-library/_All-Photos' (error code: dc4ebff3-1d74-407f-a14e-b49a883a555e)
```

### Error Code

dc4ebff3-1d74-407f-a14e-b49a883a555e

### Relevant log output

```shell-script
[2024-08-02T08:11:17.373Z] ERROR RuntimeError: APP_ARCHIVE: Archive failed caused by EINVAL: invalid argument, readlink '/opt/icloud-photos-library/_All-Photos' (error code: dc4ebff3-1d74-407f-a14e-b49a883a555e)
```

### Operating system

Ubuntu

### Execution environment

docker

### icloud-photos-sync version

v.1.3.0

### Checklist

- [X] This is an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/beta/CONTRIBUTING.md#-found-a-bug) and not [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question) or [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature)
- [X] The sync was performed a couple of times and the issue is persisting and consistent
- [X] Checked out [open and known issues](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28bug%29%2Cclass%28improvement%29%2C%22class%28known+issue%29%22)
- [X] Enabled [crash and error reporting](https://icps.steiler.dev/user-guides/cli/#enable-crash-reporting)

**Comment by steilerDev** [comment]
Archiving only works on user created Albums - see the README for more information on this:

- All assets currently in the album will be persisted in the respective folder on the machine running icloud-photos-sync
- Future syncs will ignore the folder (so those assets will not be changed/deleted)
- If the remote album is moved, the archived folder will be moved to the same location
- If the remote album is deleted, the archived folder will be put into a 'lost+found' type of folder
- Optionally all photos from the archived folder can be deleted from the iCloud Photos Library, unless they are *Favorites* (reducing cloud storage needs)

**Comment by tomwilde** [comment]
Ok that makes sense.. I guess `_All-Photos` is _Apple_ generated... I assume the workaround here is to make an album and move the media over into it?

**Comment by steilerDev** [comment]
The idea behind archiving is, that you can move photos from an album to your local machine so you can delete them remotely. Sort of a "this project is done - I don't need them anymore in the iCloud library" - see https://icps.steiler.dev/dev/motivation/

What are you trying to achieve when archiving "All Photos"?

**Comment by tomwilde** [comment]
My motivation here is to close down my iCloud usage for photo storage as it makes archival painful. :D Once I've pulled all media off I can disable it.

**Comment by tomwilde** [comment]
Update to complete this ticket:

I can confirm this works well for my scenario - the safe archival of media off my iphone and ultimately iCloud. As we discovered above the `Recents` album is 'special' and doesn't work for an `archive` command here. The workaround is to create a _new_ album - say `Offload` - put the images from `Recents` into it. Run the `sync` command and then the / `archive` command (with `--remote-delete`) and lo-and-behold it'll all work.

How Apple can make this stuff so awful is beyond me. 🤷

**Comment by tomwilde** [comment]
Final final comment:

For those wondering how to put 1000s of photos in `Recents` into the `Offload` album here's a helpful video:

https://youtu.be/ru_2lU5-v6A
