### ISSUE TITLE
Need assistance building the project (errors when running npm run build)

### ISSUE THREAD

**Issue by ido2** [steilerDev/icloud-photos-sync#565]
- I read get-started.md
- Running MacOS Sonoma (14.6)
- zsh environment
- node installed with brew

Newbie with node, and first time building the project. Would love some help.

```
cd /tmp
git clone https://github.com/steilerDev/icloud-photos-sync
cd icloud-photos-sync/app
% npm --version
10.7.0
% node --version
v18.20.4
% npm install

up to date, audited 770 packages in 1s

123 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
%
% npm run build

> icloud-photos-sync@0.0.0-development prebuild
> npm run prebuild:lint && npm run prebuild:knip


> icloud-photos-sync@0.0.0-development prebuild:lint
> npx eslint -c eslint.config.json --fix --ext .ts ./src ./test ./build


> icloud-photos-sync@0.0.0-development prebuild:knip
> npx knip --no-exit-code --config knip.config.jsonc

✂️  Excellent, Knip found no issues.

> icloud-photos-sync@0.0.0-development build
> npm run build:dev


> icloud-photos-sync@0.0.0-development build:dev
> npm run build:schema && npm run build:typescript


> icloud-photos-sync@0.0.0-development build:schema
> npx ts-node-esm build/schema.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /private/tmp/icloud-photos-sync/app/build/schema.ts
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
    at defaultLoad (node:internal/modules/esm/load:101:20)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at load (/private/tmp/icloud-photos-sync/app/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:864:28)
    at Hooks.load (node:internal/modules/esm/hooks:447:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}


```

**Comment by steilerDev** [comment]
Hmm - the error is interesting - however: Any particular reason why you want to build from source instead of using `npm` to get the package directly or going through docker?

**Comment by ido2** [comment]
Trying to add a new feature.

I am able to run it through docker just fine.

**Comment by steilerDev** [comment]
All right :) 

The only difference is the minor version of node - can you maybe try following this guide? https://stackoverflow.com/a/77993035

**Comment by ido2** [comment]
This probably fixed it for me, no idea what it means though.

--- a/app/package.json
+++ b/app/package.json
@@ -18,7 +18,7 @@
     "prebuild:lint": "npx eslint -c eslint.config.json --fix --ext .ts ./src ./test ./build",
     "prebuild:knip": "npx knip --no-exit-code --config knip.config.jsonc",
     "prebuild": "npm run prebuild:lint && npm run prebuild:knip",
-    "build:schema": "npx ts-node-esm build/schema.ts",
+    "build:schema": "node --loader ts-node/esm build/schema.ts",
     "build:typescript": "npx tsc",
     "build:dev": "npm run build:schema && npm run build:typescript",
     "build": "npm run build:dev",

**Comment by steilerDev** [comment]
yeah - I have never really understood, why node has such a hard time using ts files - once I bump the node version I'll probably have to handle this as well - so thanks for your investigation!
